blank_issues_enabled: false
contact_links:
  - name: Discussions / questions
    url: https://github.com/eklier101/apexdrive/issues
    about: For general questions, open a Feature request or Bug report with as much detail as you can.
