package httpapi

import (
	"net/http"
	"strings"

	"github.com/eklier101/apexdrive/internal/db"
	"github.com/go-chi/chi/v5"
)

var inventoryCategories=[]string{"Oil","Oil Filter","Air Filter","Cabin Filter","Fluids","Brake","Spark Plugs","Battery","Tires","Other"}
func inventoryUnit(category,unit string)string{if category=="Oil"{return "bottle"};switch category{case "Oil Filter","Air Filter","Cabin Filter","Spark Plugs","Battery":return "each"};if unit==""{return "each"};return unit}
func (a *API) inventoryRoutes(r chi.Router){r.Route("/inventory",func(r chi.Router){r.Get("/",a.listInventory);r.Get("/categories",func(w http.ResponseWriter,r *http.Request){writeJSON(w,200,inventoryCategories)});r.With(a.requireAuth).Post("/",a.createInventory);r.Put("/{id}",a.updateInventory);r.Delete("/{id}",a.deleteInventory)})}
func (a *API) listInventory(w http.ResponseWriter,r *http.Request){u:=userFromContext(r);if u==nil{writeJSON(w,200,[]map[string]any{});return};rows,err:=a.db.Query(`SELECT * FROM parts_inventory WHERE user_id=? ORDER BY category ASC,name ASC`,u.UserID);if err!=nil{writeError(w,500,err);return};writeJSON(w,200,rows)}
func (a *API) createInventory(w http.ResponseWriter,r *http.Request){b,err:=bodyMap(r);if err!=nil{writeError(w,400,"Invalid JSON");return};name:=strings.TrimSpace(text(b["name"]));if name==""{writeError(w,400,"Part name is required");return};category:=text(value(b,"category","Other"));id:=db.NewID("inv");_,err=a.db.Exec(`INSERT INTO parts_inventory(id,user_id,name,category,unit,package_size,unit_cost,quantity_on_hand,low_stock_threshold,part_number,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?)`,id,userFromContext(r).UserID,name,category,inventoryUnit(category,text(value(b,"unit","each"))),nullable(strings.TrimSpace(text(b["package_size"]))),num(value(b,"unit_cost",0)),num(value(b,"quantity_on_hand",0)),nullable(b["low_stock_threshold"]),nullable(strings.TrimSpace(text(b["part_number"]))),nullable(strings.TrimSpace(text(b["notes"]))));if err!=nil{writeError(w,500,err);return};row,_:=a.db.QueryOne(`SELECT * FROM parts_inventory WHERE id=?`,id);writeJSON(w,201,row)}
func (a *API) updateInventory(w http.ResponseWriter,r *http.Request){id:=chi.URLParam(r,"id");old,err:=a.db.QueryOne(`SELECT * FROM parts_inventory WHERE id=?`,id);if err!=nil{writeError(w,500,err);return};if old==nil{writeError(w,404,"Inventory item not found");return};if u:=userFromContext(r);u==nil||(old["user_id"]!=nil&&text(old["user_id"])!=""&&text(old["user_id"])!=u.UserID){writeError(w,403,"Not authorized");return};b,err:=bodyMap(r);if err!=nil{writeError(w,400,"Invalid JSON");return};get:=func(k string)any{if v,ok:=b[k];ok{return v};return old[k]};category:=text(get("category"));unit:=text(get("unit"));if _,ok:=b["category"];ok{unit=inventoryUnit(category,unit)};_,err=a.db.Exec(`UPDATE parts_inventory SET name=?,category=?,unit=?,package_size=?,unit_cost=?,quantity_on_hand=?,low_stock_threshold=?,part_number=?,notes=?,updated_at=datetime('now') WHERE id=?`,get("name"),category,unit,get("package_size"),num(get("unit_cost")),num(get("quantity_on_hand")),get("low_stock_threshold"),get("part_number"),get("notes"),id);if err!=nil{writeError(w,500,err);return};row,_:=a.db.QueryOne(`SELECT * FROM parts_inventory WHERE id=?`,id);writeJSON(w,200,row)}
func (a *API) deleteInventory(w http.ResponseWriter,r *http.Request){id:=chi.URLParam(r,"id");old,err:=a.db.QueryOne(`SELECT * FROM parts_inventory WHERE id=?`,id);if err!=nil{writeError(w,500,err);return};if old==nil{writeError(w,404,"Inventory item not found");return};if u:=userFromContext(r);u==nil||(old["user_id"]!=nil&&text(old["user_id"])!=""&&text(old["user_id"])!=u.UserID){writeError(w,403,"Not authorized");return};if _,err=a.db.Exec(`DELETE FROM parts_inventory WHERE id=?`,id);err!=nil{writeError(w,500,err);return};writeJSON(w,200,map[string]any{"success":true,"message":"Inventory item deleted"})}
