package httpapi

import(
 "math"
 "net/http"
 svc "github.com/eklier101/apexdrive/internal/services"
 "github.com/eklier101/apexdrive/internal/db"
 "github.com/go-chi/chi/v5"
)
func(a *API)reminderRoutes(r chi.Router){r.Route("/reminders",func(r chi.Router){r.Get("/",a.listReminders);r.Post("/",a.createReminder);r.Put("/{id}",a.updateReminder);r.Delete("/{id}",a.deleteReminder)})}
func(a *API)listReminders(w http.ResponseWriter,r *http.Request){id,ok:=a.vehicleQuery(w,r);if !ok{return};if err:=svc.SyncVehicleReminders(a.db,id);err!=nil{writeError(w,500,err);return};v,_:=a.db.QueryOne(`SELECT purchase_odometer FROM vehicles WHERE id=?`,id);f,_:=a.db.QueryOne(`SELECT MAX(odometer) max_odo FROM fillups WHERE vehicle_id=?`,id);s,_:=a.db.QueryOne(`SELECT MAX(odometer) max_odo FROM services WHERE vehicle_id=?`,id);current:=0.0;if v!=nil{current=math.Max(current,num(v["purchase_odometer"]))};if f!=nil{current=math.Max(current,num(f["max_odo"]))};if s!=nil{current=math.Max(current,num(s["max_odo"]))};rows,err:=a.db.Query(`SELECT * FROM service_reminders WHERE vehicle_id=? ORDER BY is_dismissed ASC,next_due_odometer ASC`,id);if err!=nil{writeError(w,500,err);return};writeJSON(w,200,svc.EnrichReminders(rows,current))}
func reminderValues(b map[string]any,old map[string]any)(any,any,any,any){get:=func(k string)any{if v,ok:=b[k];ok{return v};return old[k]};var miles,months,lastOdo,lastDate any;if text(get("interval_miles"))!=""{miles=num(get("interval_miles"))};if text(get("interval_months"))!=""{months=integer(get("interval_months"))};if text(get("last_serviced_odometer"))!=""{lastOdo=num(get("last_serviced_odometer"))};if text(get("last_serviced_date"))!=""{lastDate=get("last_serviced_date")};return miles,months,lastOdo,lastDate}
func nextReminder(miles,months,lastOdo,lastDate any)(any,any){var no,nd any;if miles!=nil&&lastOdo!=nil{no=num(lastOdo)+num(miles)};if months!=nil&&lastDate!=nil{nd=svc.MonthDate(lastDate,integer(months))};return no,nd}
func(a *API)createReminder(w http.ResponseWriter,r *http.Request){b,err:=bodyMap(r);if err!=nil{writeError(w,400,"Invalid JSON");return};if text(b["vehicle_id"])==""||text(b["service_type"])==""||text(b["title"])==""{writeError(w,400,"vehicle_id, service_type, and title are required");return};if _,ok:=a.ownedVehicle(w,r,text(b["vehicle_id"]));!ok{return};m,mo,lo,ld:=reminderValues(b,map[string]any{});no,nd:=nextReminder(m,mo,lo,ld);id:=db.NewID("rem");_,err=a.db.Exec(`INSERT INTO service_reminders(id,vehicle_id,service_type,title,interval_miles,interval_months,last_serviced_odometer,last_serviced_date,next_due_odometer,next_due_date,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?)`,id,b["vehicle_id"],b["service_type"],b["title"],m,mo,lo,ld,no,nd,nullable(b["notes"]));if err!=nil{writeError(w,500,err);return};row,_:=a.db.QueryOne(`SELECT * FROM service_reminders WHERE id=?`,id);writeJSON(w,201,row)}
func(a *API)updateReminder(w http.ResponseWriter,r *http.Request){id:=chi.URLParam(r,"id");old,err:=a.db.QueryOne(`SELECT * FROM service_reminders WHERE id=?`,id);if err!=nil{writeError(w,500,err);return};if old==nil{writeError(w,404,"Reminder not found");return};if _,ok:=a.ownedVehicle(w,r,text(old["vehicle_id"]));!ok{return};b,err:=bodyMap(r);if err!=nil{writeError(w,400,"Invalid JSON");return};get:=func(k string)any{if v,ok:=b[k];ok{return v};return old[k]};m,mo,lo,ld:=reminderValues(b,old);no,nd:=nextReminder(m,mo,lo,ld);_,err=a.db.Exec(`UPDATE service_reminders SET service_type=?,title=?,interval_miles=?,interval_months=?,last_serviced_odometer=?,last_serviced_date=?,next_due_odometer=?,next_due_date=?,is_dismissed=?,notes=?,updated_at=datetime('now') WHERE id=?`,get("service_type"),get("title"),m,mo,lo,ld,no,nd,boolInt(get("is_dismissed")),get("notes"),id);if err!=nil{writeError(w,500,err);return};row,_:=a.db.QueryOne(`SELECT * FROM service_reminders WHERE id=?`,id);writeJSON(w,200,row)}
func(a *API)deleteReminder(w http.ResponseWriter,r *http.Request){id:=chi.URLParam(r,"id");old,err:=a.db.QueryOne(`SELECT * FROM service_reminders WHERE id=?`,id);if err!=nil{writeError(w,500,err);return};if old==nil{writeError(w,404,"Reminder not found");return};if _,ok:=a.ownedVehicle(w,r,text(old["vehicle_id"]));!ok{return};if _,err=a.db.Exec(`DELETE FROM service_reminders WHERE id=?`,id);err!=nil{writeError(w,500,err);return};writeJSON(w,200,map[string]any{"message":"Reminder deleted successfully"})}
