package httpapi

import(
 "net/http"
 "github.com/eklier101/apexdrive/internal/db"
 "github.com/go-chi/chi/v5"
)
func(a *API)upgradeRoutes(r chi.Router){r.Route("/upgrades",func(r chi.Router){r.Get("/",a.listUpgrades);r.Post("/",a.createUpgrade);r.Put("/{id}",a.updateUpgrade);r.Delete("/{id}",a.deleteUpgrade)})}
func(a *API)listUpgrades(w http.ResponseWriter,r *http.Request){id,ok:=a.vehicleQuery(w,r);if !ok{return};rows,err:=a.db.Query(`SELECT * FROM upgrades WHERE vehicle_id=? ORDER BY date DESC,created_at DESC`,id);if err!=nil{writeError(w,500,err);return};writeJSON(w,200,rows)}
func(a *API)createUpgrade(w http.ResponseWriter,r *http.Request){b,err:=bodyMap(r);if err!=nil{writeError(w,400,"Invalid JSON");return};if text(b["vehicle_id"])==""||text(b["title"])==""{writeError(w,400,"vehicle_id, title, and category are required");return};if _,ok:=a.ownedVehicle(w,r,text(b["vehicle_id"]));!ok{return};pc,lc:=num(value(b,"part_cost",0)),num(value(b,"labor_cost",0));tc:=pc+lc;if v,ok:=b["total_cost"];ok{tc=num(v)};id:=db.NewID("upg");_,err=a.db.Exec(`INSERT INTO upgrades(id,vehicle_id,date,odometer,title,category,brand_part_number,vendor,part_cost,labor_cost,total_cost,is_installed,notes,photo_url) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,id,b["vehicle_id"],value(b,"date",today()),nullable(b["odometer"]),b["title"],value(b,"category","Performance"),nullable(b["brand_part_number"]),nullable(b["vendor"]),pc,lc,tc,boolInt(value(b,"is_installed",true)),nullable(b["notes"]),nullable(b["photo_url"]));if err!=nil{writeError(w,500,err);return};row,_:=a.db.QueryOne(`SELECT * FROM upgrades WHERE id=?`,id);writeJSON(w,201,row)}
func(a *API)updateUpgrade(w http.ResponseWriter,r *http.Request){id:=chi.URLParam(r,"id");old,err:=a.db.QueryOne(`SELECT * FROM upgrades WHERE id=?`,id);if err!=nil{writeError(w,500,err);return};if old==nil{writeError(w,404,"Upgrade not found");return};if _,ok:=a.ownedVehicle(w,r,text(old["vehicle_id"]));!ok{return};b,err:=bodyMap(r);if err!=nil{writeError(w,400,"Invalid JSON");return};get:=func(k string)any{if v,ok:=b[k];ok{return v};return old[k]};pc,lc:=num(get("part_cost")),num(get("labor_cost"));tc:=pc+lc;if v,ok:=b["total_cost"];ok{tc=num(v)};_,err=a.db.Exec(`UPDATE upgrades SET date=?,odometer=?,title=?,category=?,brand_part_number=?,vendor=?,part_cost=?,labor_cost=?,total_cost=?,is_installed=?,notes=?,photo_url=?,updated_at=datetime('now') WHERE id=?`,get("date"),get("odometer"),get("title"),get("category"),get("brand_part_number"),get("vendor"),pc,lc,tc,boolInt(get("is_installed")),get("notes"),get("photo_url"),id);if err!=nil{writeError(w,500,err);return};row,_:=a.db.QueryOne(`SELECT * FROM upgrades WHERE id=?`,id);writeJSON(w,200,row)}
func(a *API)deleteUpgrade(w http.ResponseWriter,r *http.Request){id:=chi.URLParam(r,"id");old,err:=a.db.QueryOne(`SELECT * FROM upgrades WHERE id=?`,id);if err!=nil{writeError(w,500,err);return};if old==nil{writeError(w,404,"Upgrade not found");return};if _,ok:=a.ownedVehicle(w,r,text(old["vehicle_id"]));!ok{return};if _,err=a.db.Exec(`DELETE FROM upgrades WHERE id=?`,id);err!=nil{writeError(w,500,err);return};writeJSON(w,200,map[string]any{"message":"Upgrade deleted successfully"})}
